# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-rm-bridge contributors
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args:
          - --unsafe
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies:
          - types-docutils==0.17.0
          - types-requests==2.25.11
          - types-PyYAML==6.0.7
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: insert-license
        name: Insert license headers (shell-style comments)
        files: '(?:^|/)(?:.*\.(?:py|sh|toml|ya?ml)|Dockerfile|Makefile)$'
        exclude: '(?:^|/)\..+|^docs/Makefile$'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header.txt
          - --comment-style
          - "#"
      - id: insert-license
        name: Insert license headers (XML-style comments)
        files: '\.(?:html|md|xml)$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header.txt
          - --comment-style
          - "<!--| ~| -->"
      - id: insert-license
        name: Insert license headers (C-style comments)
        files: '\.(?:css|js|ts)$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header.txt
          - --comment-style
          - "/*| *| */"
      - id: insert-license
        name: Insert license headers (reST comments)
        files: '\.rst$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header.txt
          - --comment-style
          - "..|  |"
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.0
    hooks:
      - id: reuse
